[package]
name = "blockchain2_exercise_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sha256 = "1.0.3"
ripemd = "0.1.3"
whirlpool = "0.10.4"
sha2 = "0.10.6"
hex-literal = "0.3.4"